name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: askinkeles
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Europe/Istanbul
          
          # ğŸ† BAÅARILAR VE MADALYALAR
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          
          # ğŸ’» KODLAMA ALIÅKANLIKLARI (Hangi saatlerde aktifsin?)
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
          
          # ğŸ“Š DÄ°L Ä°STATÄ°STÄ°KLERÄ° (DetaylÄ±)
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          
