name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Her gece 00:00'da çalışır
  workflow_dispatch: # Manuel çalıştırma izni
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: askinkeles
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Europe/Istanbul
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
